apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: awx-dev

image: rancher/k3s:v1.30.3-k3s1

kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6550"

ports:
  - port: 8080:30080
    nodeFilters:
      - server:0

options:
  k3d:
    timeout: "300s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
      - arg: --disable=servicelb
        nodeFilters:
          - server:0
