apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: awx-dev

servers: 1
agents: 0

image: rancher/k3s:v1.30.3-k3s1

kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6550"

volumes:
  - volume: ./data/storage:/var/lib/rancher/k3s/storage
    nodeFilters:
      - server:0

ports:
  - port: 8080:30080
    nodeFilters:
      - server:0

options:
  k3d:
    wait: true
    timeout: "300s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
      - arg: --disable=servicelb
        nodeFilters:
          - server:0
