apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  admin_user: admin
  admin_password_secret: awx-admin-password
  secret_key_secret: awx-secret-key

  service_type: NodePort
  nodeport_port: 30080

  postgres_storage_class: local-path

  csrf_cookie_secure: "False"
  session_cookie_secure: "False"
  extra_settings:
    - setting: CSRF_TRUSTED_ORIGINS
      value: "['http://localhost:8080']"
